require('config.autocmd')
require('config.clang-format')
require('config.comment')
require('config.fix_comment_strings')
require('config.lsp')
-- require('config.termdebug')
require('config.terminal')
require('config.ui2')
require('config.window-management')
require('config.wrap')
